import json

from pydantic import BaseModel, Field
from guardrails import Guard


# ============================================================
# OUTPUT SCHEMA
# ============================================================

class AnswerValidation(BaseModel):
    answer: str = Field(
        ...,
        description=(
            "The final answer generated by "
            "the Hybrid RAG system."
        ),
    )


# ============================================================
# GUARDRAILS
# ============================================================

guard = Guard.for_pydantic(
    output_class=AnswerValidation
)


# ============================================================
# VALIDATE ANSWER
# ============================================================

def validate_answer(
    answer: str,
):
    """
    Validate a RAG answer using Guardrails.

    Guardrails Pydantic parsing expects the
    generated structured output as serialized
    JSON rather than a Python dictionary.
    """

    if answer is None:
        raise ValueError(
            "Answer cannot be None."
        )

    if not isinstance(
        answer,
        str,
    ):
        answer = str(
            answer
        )

    answer = answer.strip()

    if not answer:
        raise ValueError(
            "Answer cannot be empty."
        )

    payload = json.dumps(
        {
            "answer": answer
        },
        ensure_ascii=False,
    )

    # IMPORTANT:
    # Use parse() with JSON text.
    result = guard.parse(
        payload
    )

    return result